apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-application
  namespace: default
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    repoURL: https://github.com/Benvovi/demo-dev
    targetRevision: HEAD
    path: applications
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
